sudo: false
language: rust

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
    sources:
      - kalakris-cmake

rust:
  - nightly
  - stable
  - 1.16.0

before_script:
  - |
      if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
        cargo install -f cargo-travis;
        export PATH=$HOME/.cargo/bin:$PATH;
      fi

script:
  - |
      if [ "$TRAVIS_RUST_VERSION" == "1.13.0" ]; then
        for crate in rmp rmp-serialize rmpv; do
          (cd $crate && cargo test --verbose);
        done;
      else
        cargo test --all --verbose;
      fi

after_success:
  - |
      if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
        cargo coveralls --all;
      fi
