sudo: false
language: rust

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake
    sources:
      - kalakris-cmake

rust:
  - nightly
  - stable
  - 1.31.1

before_script:
  - |
      if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
        cargo install -f cargo-travis;
        export PATH=$HOME/.cargo/bin:$PATH;
      fi

script:
  - |
      cargo test --all --verbose;

after_success:
  - |
      if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
        cargo coveralls --all;
      fi

# tests require a higher rust version, but build should still function on 1.16.0
matrix:
  include:
    - rust: 1.16.0
      script:
        - |
            cargo build --all --verbose
