language: rust

sudo: false

# Necessary for `travis-cargo coveralls --no-sudo`.
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev

rust:
  - stable
  - nightly

env:
  - CRATE=rmp
  - CRATE=rmp-serialize
  - CRATE=rmp-serde
  - CRATE=rmp-serde-tests
  - CRATE=rmpv

# Load travis-cargo.
before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH

script:
  - |
    if [ "$CRATE" = "rmp-serde-tests" ]; then
        if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then
            (cd $CRATE && cargo test);
        else
            (cd $CRATE && cargo test --features=with-syntex --no-default-features);
        fi
    else
        (cd $CRATE && cargo test);
    fi

# Measure code coverage and upload to coveralls.io.
after_success:
  - (cd $CRATE && travis-cargo coveralls --no-sudo)
