[package]
name = "rmpv-tests"
version = "0.0.0"
authors = ["Evgeny Safronov <division494@gmail.com>"]
publish = false

[dependencies]
serde = "1"
serde_derive = "1"
rmp-serde = { version = "0.13", path = "../rmp-serde" }
rmpv = { features = ["with-serde"], path = "../rmpv" }
