[package]
name = "rmpv-tests"
version = "0.0.0"
authors = ["Evgeny Safronov <division494@gmail.com>"]
publish = false

[dependencies]
serde = "^0.9"
rmp-serde = "^0.12"
rmpv = { version = "^0.2.0", features = ["with-serde"], path = "../rmpv" }
