[package]
name = "rmp"
version = "0.8.3"
authors = ["Evgeny Safronov <division494@gmail.com>"]
license = "MIT"
description = "Pure Rust MessagePack serialization implementation"
repository = "https://github.com/3Hren/msgpack-rust"
documentation = "https://docs.rs/rmp"
readme = "../README.md"
keywords = ["msgpack", "MessagePack"]
categories = ["encoding"]

[dependencies]
byteorder = "1"
num-traits = "^0.1"

[dev-dependencies]
quickcheck = "0.3"
