[package]
name = "rmp"
version = "0.8.0"
authors = ["Evgeny Safronov <division494@gmail.com>"]
license = "MIT"
description = "Pure Rust MessagePack serialization implementation"
repository = "https://github.com/3Hren/msgpack-rust"
documentation = "https://3hren.github.io/msgpack-rust/rmp/index.html"
readme = "../README.md"
keywords = ["msgpack", "MessagePack"]

[dependencies]
byteorder = "1"
num-traits = "^0.1"

[dev-dependencies]
quickcheck = "0.3"
