[package]
name = "rmp-serde"
version = "0.13.3"
authors = ["Evgeny Safronov <division494@gmail.com>"]
license = "MIT"
description = "Serde bindings for RMP"
repository = "https://github.com/3Hren/msgpack-rust"
documentation = "https://docs.rs/rmp-serde"
readme = "../README.md"
keywords = ["msgpack", "MessagePack", "serde", "serialization"]

[dependencies]
byteorder = "1"
serde = "1"
rmp = "0.8"

[dev-dependencies]
serde_bytes = "0.10"
serde_derive = "1"
